language: java
sudo: false
services:
  - mongodb
jdk:
  - openjdk7
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install:
  - mvn clean validate
script:
  - mvn compile package
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b5f5d5c337a7af9276
    on_success: change
    on_failure: always
    on_start: never
  irc:
    - irc.freenode.org#jrds
addons:
  sonarcloud:
    organization: rrd4j
    token:
      secure: "jQYJJtZwMLL584h/D3DMyF/N2GUHVucEAsH6EbvlPPhEkArZh97/HFOMLJhqxi/RRndpd0fVIUqwToIBfYepnkgZlsbLEVFztZoFqIWygCOu1rbTXVpU0mTX/dsxxzPyyJI3YhmvWQpwuKQrSk8DL9RUOr6niSbr9wgloPIPgtQ="
matrix:
  include:
      # Sonarcloud don't work on jdk11 yet
      # See https://github.com/SonarSource/sonar-scanner-maven/pull/47
    - jdk: openjdk8
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent compile package sonar:sonar deploy --settings deploy-settings.xml
      on:
          branch: master
